# Generated by Django 4.2.7 on 2025-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sala', models.DecimalField(blank=True, decimal_places=2, help_text='Sala amount in ₹', max_digits=12, null=True)),
                ('instalments', models.IntegerField(blank=True, help_text='Number of instalments', null=True)),
                ('auction_bid', models.CharField(blank=True, help_text='Auction bid percentage or amount', max_length=50, null=True)),
                ('period', models.CharField(blank=True, help_text='Period (e.g., Months, Weeks)', max_length=50, null=True)),
                ('instalment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Instalment amount in ₹', max_digits=12, null=True)),
                ('auction_date', models.TextField(blank=True, help_text='Auction date information', null=True)),
                ('header_color', models.CharField(default='gradient-primary', help_text='Header color class (e.g., gradient-primary, bg-gradient-to-r from-blue-500 to-blue-700)', max_length=100)),
                ('coming_soon', models.BooleanField(default=False, help_text='Mark as coming soon if scheme details are incomplete')),
                ('is_active', models.BooleanField(default=True, help_text='Show this scheme on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
